### PR TITLE
Update nanoid to 3.x (and fix failing unit test)

### LINKED ISSUE #54: Update nanoid to 3.x (latest)
Except for all the nice enhancements in 3.x over 2.x, in my specific use case I've encountered the following issue: Using webpack 5, I'm bundling a Vue 2.x app that uses vue-simple-portal. If my understanding is correct, since vue-simple-portal uses esm, then it break when trying to import a cjs module (for unknown reason webpack 5 can't detect it as such). I'll do a PR as well.

### PR DESCRIPTION
**Pull request by cjblomqvist**
Fixes #54

### CODE REVIEW

**Comment by JeffBeltran** [comment]
would this be related to this error i'm getting?

```
ERROR in ./node_modules/@linusborg/vue-simple-portal/dist/index.mjs 10:0-35
Module not found: Error: Can't resolve 'nanoid/non-secure
```

**Comment by cjblomqvist** [comment]
@JeffBeltran - yep, exactly

**Comment by ChristianKienle** [comment]
I have a very similar issue.

What I did:

- Checked out this PR
- Used it instead of what is currently released on NPM
- Made sure that everything works (as it did in the past)

In my case I was still using Webpack 4 but had Vue Simple Portal wrapped inside another module which was built using rollup. 
@LinusBorg can this be merged & released? :)

**Comment by LinusBorg** [comment]
Attempted at the weekend but my brain was on vacation mode and didn't manage ^^

Will give it a try tomorrow on the holiday we have here.

**Comment by ChristianKienle** [comment]
> Attempted at the weekend but my brain was on vacation mode and didn't manage ^^
> 
> Will give it a try tomorrow on the holiday we have here.

You are best. By the way: Happy new year Thorsten. May everything go according to plan – or better.

**Comment by LinusBorg** [comment]
this would be published now if I didn't have some weird publishing errors with npm. I'll report here when I got those resolved.

**Comment by LinusBorg** [comment]
Ok, 0.1.5 is up. yarn allowed me to publish, npm did not ^^

**Comment by ChristianKienle** [comment]
Thank you very much Thorsten. ☕ is on its way.

**Pull request merged**
