### PR TITLE
Add Package Types

### LINKED ISSUE #10: Typescript annotations

### PR DESCRIPTION
**Pull request by alexsasharegan**
Closes #10

### CODE REVIEW

**Comment by LinusBorg** [comment]
Thanks :)

Will need to find some time to test this and possibly try and add actual types for the ``Portal` component instead of `any`, but this is immensly helpful :)

**Comment by alexsasharegan** [comment]
Yeah, SFC's are shimmed as `any` in the Vue CLI, and I think it tends to avoid more problems than it would solve by being typed as a proper component, but I would love to know if there's a better way.

**Comment by alexsasharegan** [comment]
Here's one possible way to type the component, but it has the drawback of advertising internal methods:

```ts
import Vue, { Component, PluginFunction } from 'vue'

export interface SimplePortalOptions {
  name?: string
}

export interface SimplePortalConfig {
  selector: string
}

export var config: Readonly<SimplePortalConfig>
export var setSelector: <T extends string>(selector: T) => T

interface PortalMethods {
  getTargetEl(): void | HTMLElement | null
  insertTargetEl(): void
  mount(): void
  unmount(): void
}

export interface PortalProps {
  disabled?: boolean
  prepend?: boolean
  selector?: string
  tag?: string
}

export var Portal: Component<void, PortalMethods, void, PortalProps>

var install: PluginFunction<SimplePortalOptions>
export default install
```

**Comment by fuzzzerd** [comment]
Any chance of this getting merged and pushed as a package update? Typescript support would be useful.

**Comment by sattes-faction** [comment]
Hello guys,
any chance that this is going to be merged?

**Comment by Finrod927** [comment]
For those who need TS definition, you can create a `.d.ts` file in your `src` folder with that definition, it should work:

```
declare module '@linusborg/vue-simple-portal' {
  import { PluginFunction } from 'vue'

  export interface SimplePortalOptions {
    name?: string
  }

  export interface SimplePortalConfig {
    selector: string
  }

  export const config: Readonly<SimplePortalConfig>
  export const setSelector: <T extends string>(selector: T) => T
  export const Portal: any

  const install: PluginFunction<SimplePortalOptions>
  export default install
}
```

**Pull request closed without merging**
